# Generated by Django 5.0.4 on 2024-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitlogapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="sets",
        ),
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
