# Generated by Django 5.0.4 on 2024-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitlogapp", "0005_remove_profile_body_weight_bodyweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
