# Generated by Django 5.0.4 on 2024-09-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitlogapp", "0008_customuser_change_password_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="custom_username",
            field=models.CharField(
                max_length=150, null=True, unique=True, verbose_name="ユーザー名"
            ),
        ),
    ]
