#共通の基本設定のファイル
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - webnet

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  postgres-data:

networks:
  webnet:
