# 開発環境用のオーバーライドファイル
version: '3'

services:
  web:
    ports:
      - '8000:8000'
    environment:
      - DEBUG=True

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
