#共通の基本設定のファイル
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - '8000'
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  postgres-data:

networks:
  webnet:
