# 本番環境用のオーバーライドファイル
version: '3'

services:
  nginx:
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/generate-certs.sh:/etc/nginx/generate-certs.sh
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /etc/nginx/generate-certs.sh

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - webnet
