version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - '80:8000'
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
